### ISSUE TITLE
Closing diff window does not reliably terminate webdiff command

### ISSUE THREAD

**Issue by danvk** [danvk/webdiff#66]
Here's an example session:

```
$ webdiff https://github.com/hammerlab/cycledash/pull/200/files
Loading pull request hammerlab/cycledash#200 from github...
  __tests__/pdifftests/examine-charted.png...
  __tests__/pdifftests/examine-sorted.png...
  __tests__/pdifftests/examine-tooltip.png...
  __tests__/pdifftests/examine.png...
Serving diffs on http://localhost:51234
Close the browser tab or hit Ctrl-C when you're done.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51342)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

^C%
```

**Comment by danvk** [comment]
I really hope this is fixed.

**Comment by danvk** [comment]
Alas, it is not! My theory is that the `beforeunload` event doesn't always fire, so the server doesn't always get a shutdown notice. Maybe maintaining a websocket would work better?
