### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by danvk** [danvk/webdiff#86]
I'm seeing this logged when I `git webdiff d3aa242` in cycledash:

```
ERROR:webdiff.app:Exception on /b/image/DEVELOP.md [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/webdiff/app.py", line 118, in get_image
    if not mime_type.startswith('image/') or enc is not None:
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by danvk** [comment]
I'm unable to reproduce this (not to future self: please include _both_ SHAs on the `git webdiff` command!).
